#!/usr/bin/env python3
"""Generate static HTML entrypoints for route-backed Rocket Questions pages."""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import unicodedata
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TEST1_ROOT = ROOT / "test1"
SOURCE_INDEX = ROOT / "index.html"
TRACK_MANIFESTS = {
    "netc-121": ROOT / "courses" / "NETC-121" / "notes-manifest.json",
    "network-plus": ROOT / "courses" / "Network+" / "notes-manifest.json",
    "security-plus": ROOT / "courses" / "Security+" / "notes-manifest.json",
}
MARKER = "<!-- Generated by scripts/build_route_entrypoints.py -->\n"
GENERATED_MIRROR_ROOTS = [ROOT, TEST1_ROOT]
MIRRORED_SUPPORT_PATHS = [
    "app.js",
    "styles.css",
    "alex.jpg",
    "rocket_icon.png",
    "changelog.md",
    "tour_question_bank.csv",
    "course-configs",
    "courses",
]


def build_entrypoint_html() -> str:
    source = SOURCE_INDEX.read_text(encoding="utf-8")
    while source.startswith(MARKER):
        source = source[len(MARKER):]
    return f"{MARKER}{source}"


def render_entrypoint_html(source_html: str, target_file: Path, mirror_root: Path) -> str:
    relative_prefix = os.path.relpath(mirror_root, target_file.parent).replace("\\", "/")
    asset_prefix = "./" if relative_prefix == "." else f"{relative_prefix}/"
    replacements = {
        'href="./rocket_icon.png': f'href="{asset_prefix}rocket_icon.png',
        'href="./styles.css': f'href="{asset_prefix}styles.css',
        'src="./alex.jpg"': f'src="{asset_prefix}alex.jpg"',
        'src="./rocket_icon.png': f'src="{asset_prefix}rocket_icon.png',
        '"./course-configs/': f'"{asset_prefix}course-configs/',
        '`./app.js?q=${REQUIRED_APP_VERSION}`': f'`{asset_prefix}app.js?q=${{REQUIRED_APP_VERSION}}`',
    }
    rendered = source_html
    for original, replacement in replacements.items():
        rendered = rendered.replace(original, replacement)
    return rendered


def slugify_segment(text: str, max_length: int = 64) -> str:
    ascii_text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")
    base = re.sub(r"[^a-z0-9]+", "-", ascii_text.lower()).strip("-")
    return (base or "note")[:max_length].rstrip("-") or "note"


def build_note_slug(note_path: str, seen_routes: set[str]) -> str:
    parts = [part for part in note_path.replace("\\", "/").split("/") if part]
    if not parts:
        return "note"

    slug_parts = []
    for part in parts[:-1]:
        slug_parts.append(slugify_segment(part))

    stem = Path(parts[-1]).stem
    slug_parts.append(slugify_segment(stem))
    route = "/".join(slug_parts)
    if route not in seen_routes:
        seen_routes.add(route)
        return route

    digest = hashlib.sha1(note_path.encode("utf-8")).hexdigest()[:8]
    deduped = f"{route}-{digest}"
    seen_routes.add(deduped)
    return deduped


def flatten_note_paths(nodes: list[dict[str, object]]) -> list[str]:
    paths: list[str] = []
    for node in nodes:
        if node.get("type") == "directory":
            paths.extend(flatten_note_paths(list(node.get("children") or [])))
            continue
        if node.get("type") == "file" and isinstance(node.get("path"), str):
            paths.append(str(node["path"]).strip().replace("\\", "/"))
    return paths


def load_manifest_note_paths(manifest_path: Path) -> list[str]:
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    return flatten_note_paths(list(payload.get("roots") or []))


def reset_mirror_support_tree(mirror_root: Path) -> None:
    if not mirror_root.exists():
        mirror_root.mkdir(parents=True, exist_ok=True)
    if mirror_root == ROOT:
        return
    for relative_path in MIRRORED_SUPPORT_PATHS:
        source = ROOT / relative_path
        target = mirror_root / relative_path
        if target.exists():
            if target.is_dir():
                shutil.rmtree(target)
            else:
                target.unlink()
        if source.is_dir():
            shutil.copytree(source, target)
        else:
            shutil.copy2(source, target)


def build_screen_entrypoints(html: str, mirror_root: Path) -> int:
    screen_route_dirs = [mirror_root]
    for track_slug in TRACK_MANIFESTS:
        screen_route_dirs.extend([
            mirror_root / track_slug,
            mirror_root / track_slug / "notes",
            mirror_root / track_slug / "pbqs",
            mirror_root / track_slug / "practice" / "weeks",
            mirror_root / track_slug / "practice" / "setup",
            mirror_root / track_slug / "practice" / "quiz",
            mirror_root / track_slug / "practice" / "review",
        ])
    screen_route_dirs.extend([
        mirror_root / "courses" / "Network+" / "practice-quiz" / "live",
        mirror_root / "courses" / "Network+" / "practice-quiz" / "results",
    ])
    for route_dir in screen_route_dirs:
        route_dir.mkdir(parents=True, exist_ok=True)
        target = route_dir / "index.html"
        target.write_text(render_entrypoint_html(html, target, mirror_root), encoding="utf-8")
    return len(screen_route_dirs)


def build_note_entrypoints(html: str, mirror_root: Path) -> int:
    built = 0
    route_map: dict[str, dict[str, str]] = {}
    generated_roots = [mirror_root / "workspace", *(mirror_root / track_slug for track_slug in TRACK_MANIFESTS)]
    for generated_root in generated_roots:
        if generated_root.exists():
            shutil.rmtree(generated_root)
    for track_id, manifest_path in TRACK_MANIFESTS.items():
        track_dir = mirror_root / track_id / "notes"
        if track_dir.exists():
            shutil.rmtree(track_dir)
        note_paths = load_manifest_note_paths(manifest_path)
        track_dir = mirror_root / track_id / "notes"
        track_dir.mkdir(parents=True, exist_ok=True)
        route_map[track_id] = {}
        seen_routes: set[str] = set()
        for note_path in note_paths:
            slug_route = build_note_slug(note_path, seen_routes)
            target = track_dir / f"{slug_route}.html"
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(render_entrypoint_html(html, target, mirror_root), encoding="utf-8")
            route_map[track_id][slug_route] = note_path
            built += 1
    (mirror_root / "route-map.json").write_text(
        json.dumps(route_map, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return built


def main() -> None:
    html = build_entrypoint_html()
    summaries = []
    for mirror_root in GENERATED_MIRROR_ROOTS:
        reset_mirror_support_tree(mirror_root)
        note_count = build_note_entrypoints(html, mirror_root)
        screen_count = build_screen_entrypoints(html, mirror_root)
        summaries.append(f"{mirror_root.name or '.'}: {screen_count} screen entrypoint file(s), {note_count} note entrypoint file(s)")
    print("Built route entrypoints for " + "; ".join(summaries) + ".")


if __name__ == "__main__":
    main()
